# Exercise 05

* Task 1: Working with the `%` operator
* Task 2: Writing functions that take several parameters
* Tasks 3&4: Working with dictionaries
* Task 5: Coding on paper (control flow)5

## Task 1 - the `%` operator

Use the `%` operator and a loop of your choice to find out:
* how many numbers from 1 to 100 are divisible by 7? save them into a list and print out the list
* by which numbers from 2 to 30 is `462231` divisible? save them into a list and print out the list

In [ ]:
# Numbers from 1 to 100 that are divisible by 7

In [ ]:
# Numbers from 2 to 30 by which 462231 is divisible

## Task 2 - Functions with several parameters

Write the function `sum_and_product` that takes three numeric arguments (name them as you like) and has two return values: the sum (`+`) of all 3, and the product (`*`) of all three. Make sure to test for valid input (all three input parameters have to be numeric, else return an error message of your choice); and make sure to add a docstring.

In [ ]:
def sum_and_product():
    '''
    docstring
    '''
    # YOUR CODE HERE
    raise NotImplementedError()

In [ ]:
# test if it worked for valid input

In [ ]:
# see what happens if input is invalid

## Task 3 - Dictionaries back at the ice cream shop

We are back at the ice cream shop. Your employee is still using lists to store ice cream sales data, but you want to show them that using dictionaries is a much better idea! 

Create a dictionary `icedict` where:
* keys ... ice cream flavour tuples; 
* values ... numbers of time this ice cream flavour tuple has been sold (i.e. the number of times it appears on the list);
* for example, for the key `(yoghurt, mint)`, the `icedict[('yoghurt', 'mint')]` should contain the value `2`

There are many ways to achieve this. **Some hints:**
* start with an empty dictionary
* use a loop to add key-value pairs
* decide how to handle in your code the two different cases:
    * case 1: your loop arrives at a key that is not yet in the dictionary
    * case 2: your loop arrives at a key that is already in the dictionary

In [ ]:
# run this cell to define the icecream_sold variable
icecream_sold = [
    ('yoghurt', 'mint'), ('cookie', 'cookie'), ('caramel', 'yoghurt'), ('yoghurt', 'straciatella'), ('caramel', 'straciatella'),
    ('vanilla', 'yoghurt'), ('hazelnut', 'banana'), ('straciatella', 'straciatella'), ('cookie', 'cookie'), ('cookie', 'caramel'),
    ('banana', 'straciatella'), ('cheesecake', 'cookie'), ('chocolate', 'chocolate'), ('mint', 'hazelnut'), ('hazelnut', 'cheesecake'),
    ('caramel', 'vanilla'), ('yoghurt', 'mint'), ('cheesecake', 'vanilla'), ('chocolate', 'cookie'), ('mint', 'strawberry'), ('cookie', 'strawberry'),
    ('hazelnut', 'vanilla'), ('yoghurt', 'strawberry'), ('strawberry', 'chocolate'), ('cheesecake', 'cookie'), ('straciatella', 'vanilla'),
    ('caramel', 'banana'), ('mint', 'straciatella'), ('caramel', 'strawberry'), ('cookie', 'strawberry'), ('caramel', 'yoghurt'),
    ('strawberry', 'mint'), ('mint', 'hazelnut'), ('banana', 'hazelnut'), ('straciatella', 'banana'), ('mint', 'straciatella'),
    ('cheesecake', 'chocolate'), ('mint', 'yoghurt'), ('cookie', 'banana'), ('cheesecake', 'mint'), ('banana', 'straciatella'),
    ('mint', 'straciatella'), ('straciatella', 'straciatella'), ('cookie', 'mint'), ('cookie', 'straciatella'), ('banana', 'caramel'),
    ('mint', 'cheesecake'), ('chocolate', 'banana'), ('cheesecake', 'vanilla'), ('vanilla', 'yoghurt'), ('hazelnut', 'yoghurt'),
    ('hazelnut', 'cookie'), ('strawberry', 'cookie'), ('yoghurt', 'cheesecake'), ('cheesecake', 'banana'), ('vanilla', 'hazelnut'), 
    ('cookie', 'strawberry'), ('mint', 'straciatella'), ('cheesecake', 'vanilla'), ('cookie', 'strawberry'), ('cookie', 'strawberry')
]

In [ ]:
# define your dictionary
# icedict = ...

In [ ]:
# you can run this cell to test whether you defined your dictionary correctly
assert icedict[('chocolate', 'cookie')]==1
assert icedict[('straciatella', 'straciatella')]==2
assert icedict[('cheesecake', 'vanilla')]==3
# if running this cell throws no errors, it means you have defined your icedict correctly!

# Task 4: Dictionaries at the bank

We provide you with the dictionary `bank_year` which contains data on movements from your bank account over the period of a year. We also give you the the variable `balance_before` which contains the balance on your account *before* the start of the `bank_year`. 

Keys are days of the year represented as `int` (from 0 to 364, where 0 is January 1st, ..., and 364 is December 31). 

Values are transactions. Positive values are payments to the account, negative values are withdrawals from the account. Values can have different types:
* `list` (of ints) (if there were several transactions that day)
* `int` (if there was only 1 transaction that day)
* `bool` (value `False` - if there was no transaction that day)

However, the data is not very clean. Your tasks:
1. Make sure to delete all key-value pairs where the key is **not** of integer type. Be careful not to delete keys within a loop that iterates over keys!
2. Next, make sure that all days of the year (i.e. all integers from 0 to 364) are represented in the `bank_year` dictionary. If a day is not yet in the dictionary, let's assume that there were no account movements on that day - add the day as key to the `bank_year` dictionary, with the value `False`.
3. Make sure that all values are of type `list`, `int`, or `bool`. If you find some values that are of type `str`, convert them into `int`.
4. Make a new dictionary, `bank_balance`, that contains the balance on your account at the end of each day as values. 
5. Find out:
    * on how many days there were no transactions at all?
    * on how many days your account balance was `>200000`?
    * what is your account balance on the evening of December 31? Did you get rich?
    * how much did you **withdraw** from your account over the entire year? 
    * how much did you **deposit** to your account over the entire year?

**Hint for subtask4**: Make a new dictionary where keys are days, and values are **account balance** at the end of each day, i.e. the sum of the balance before, and **all** past transactions. For example, if the balance on your account was 0, and your transactions on day 1 are [100,-30], then the balance at the end of day 1 on your account will be `70`.

In [ ]:
# Run this cell to define the balance_before and the bank_year variables.
balance_before = 1500
bank_year = {
 0: [665, 626, -303, -449],
 1: [-392, -62, 201],
 2: [826, 486, -324, -398],
 3: "-273",
 4: -327,
 5: 66,
 8: [-364, 14, 718],
 9: False,
 10: False,
 11: [-186, 69, 308, 751, 578],
 12: [404, 928, 17],
 13: [335, -307, -155, -380],
 14: [477, 388, 137, 593],
 15: [-181, 399, 510, 868],
 16: [-238, 267, -71],
 17: [280, 262],
 18: 529,
 19: [701, 806],
 20: [357, 322],
 21: [629, 860],
 22: [335, 647, -463],
 23: [674, -216, 300],
 24: [597, 50, -105, 135, 873],
 25: -565,
 26: False,
 27: [720, 571, -214],
 28: [-75, 213, 376],
 29: 72,
 30: -141,
 31: [75, 559],
 32: [890, 792, -334, 425],
 33: [228, 361, -281],
 34: 863,
 35: 616,
 36: 152,
 37: [132, 149, -225, 117],
 38: [-4, 157, 280, -446],
 39: 1117,
 40: [285, 5, -67, -384],
 41: -354,
 42: [-92, 415, 692, -361, 674],
 43: [-277, 637],
 44: [93, 343, -180, 547, 661],
 45: [-9, -169, 487, 280, -22],
 46: [-405, -171, 413],
 47: False,
 48: [-230, -457, -342, 465, -371],
 49: [806, 956, 726],
 50: [594, -205, -420, -129],
 51: [789, -379, 123],
 52: [235, -269, -267, -474, 638],
 53: [-94, 635],
 57: 1162,
 58: -154,
 59: 440,
 60: [696, 887, 56, 262],
 61: 626,
 62: [162, 376],
 63: 363,
 64: [204, -165, 144, 111, -246],
 65: -15,
 66: -12,
 67: [760, 79, 25],
 68: [953, -221],
 69: [-209, 784, 398, 945, 77],
 70: -300,
 71: [196, 304],
 72: [579, 70, 52, 723],
 73: 99,
 78: 671,
 79: 1010,
 80: [200, 329, -77],
 81: [-172, -470, 931, 610, -490],
 82: [377, 363, 245, 995],
 83: [988, 135, -167],
 84: False,
 85: [304, 588],
 86: [-193, -380, 194, 995, -60],
 87: [-106, -392],
 88: [-232, -175, -327],
 89: -196,
 90: [-168, 552, -314],
 91: [147, -341, 560],
 92: [276, 701, 941, 66, 343],
 93: 125,
 94: [-155, 596],
 95: -361,
 96: 376,
 97: [-481, 135],
 98: [-487, 618],
 102: [-25, -352],
 103: [411, 86, 968, 718, -277],
 104: 395,
 105: [591, -221],
 106: [-304, 931, 238],
 107: [-155, -404, 538, 155, 444],
 108: 975,
 112: [-254, -92, 724, 758],
 113: [172, 541],
 114: 371,
 115: [682, 467, 878, 309, 738],
 116: [433, 210, -59, 3],
 117: [799, -139, 555, -284, 972],
 118: 746,
 119: [945, 610, -214, -125],
 120: [-114, 873, 324, -317, 845],
 121: [265, -334, 328, 460],
 122: [-394, 731, 653],
 123: [-428, 685],
 124: -265,
 125: [743, 417, 486],
 126: [712, 608, 90],
 127: 135,
 128: False,
 129: [166, 292, 549, 450, -352],
 130: [-105, 271, -63],
 131: -483,
 132: [341, 235],
 133: 1001,
 139: [836, 917, 347, 36, 885],
 140: [369, 889],
 141: [778, 250, 180, 431, 150],
 142: [533, -276, 64, 897],
 143: [-352, 403, 467, 588],
 144: [-180, 984, 760, 342],
 145: [987, -421, 332, 887],
 146: 125,
 147: [-334, 614, 593, -111],
 148: [560, -258, -389, 557],
 149: [208, 137, -295, 880, 6],
 150: -279,
 151: "852",
 152: [-298, -143, -42, 89, 68],
 153: [941, 134, 559, 939],
 154: "-268",
 155: [-66, -77],
 156: [-479, 51, 396],
 157: 70,
 158: [327, 984, -173, -382],
 159: 1024,
 160: [251, -327, -432],
 161: 1070,
 162: [-156, 435, 977, 195, 469],
 163: [386, 488, 396, 590],
 164: 728,
 165: [-223, 802],
 166: [754, 304],
 167: [983, -390],
 168: [-290, 423, 968],
 169: 47,
 170: -689,
 171: "-441",
 172: 631,
 173: [859, -449, 343],
 174: 881,
 175: [592, 712, 874, -122, 871],
 176: [-441, -317, -425, 841, 446],
 177: [-138, -466, 919, 974, 547],
 178: [81, 844, 484, -342],
 179: [99, -54, 193, -226, 568],
 180: [402, 123, 279, 952, -201],
 181: [878, 975, 128, 369, 60],
 182: 91,
 183: 425,
 184: [345, 640, 47],
 185: [878, 892, 339, 727],
 186: "-510",
 187: [-150, 696],
 188: [-132, 232, 509, 619, 587],
 189: [868, 146],
 190: -432,
 191: [498, 435, -447, -439],
 192: [-100, 673],
 196: [-348, 526, 58, 31],
 197: [436, 399],
 198: [424, 960, 475],
 199: "892",
 200: [9, 672, 381, 809],
 201: [-435, -267, 298, -82],
 202: [324, 429, -301],
 203: [-325, 812],
 204: [-207, 25, -436],
 205: [339, 558, 193, 464, 787],
 206: [179, 411, 33, 275],
 207: [255, -251],
 208: [615, -264, -355, 207],
 209: [-481, 697],
 210: [272, 767],
 211: [918, 116],
 212: 645,
 213: -519,
 214: [950, 634, 676, 809, 75],
 215: 667,
 216: [-475, 553, 722, 907],
 217: [95, -445, -148, 954, -469],
 218: 149,
 219: [125, -112, -412, 438, -391],
 220: [154, 337, 405, 251, 582],
 221: [552, 385, -473, -278],
 222: [844, 939, 989, 103, 396],
 223: [700, -62, 46, 644],
 "email": "example@itu.dk",
 (2022, 12, 31): "YYYY, MM, DD",
 224: 512,
 225: [-338, 930, 219],
 226: 524,
 227: [367, 33, -470],
 228: 542,
 229: [351, 281, -173],
 230: False,
 231: -439,
 232: -468,
 233: [-325, 458, 839, 519],
 234: 151,
 235: 769,
 236: [-275, 459, 352, 906, -244],
 237: 1092,
 238: [881, -167, 64, 852, 798],
 239: 464,
 240: [-427, 845, 217],
 241: [364, -485],
 242: 1168,
 243: [574, -276],
 244: 698,
 245: [-29, -305],
 246: [178, -352, -390, -79],
 247: [413, -330, 833, -94, 641],
 248: [991, 687, -159, -181, 828],
 249: [130, -353, -150, 322, -421],
 250: False,
 251: [-451, -15, 631],
 252: [555, 292],
 253: [549, -407],
 254: 577,
 255: [24, 770, 164],
 256: [-186, 550],
 257: -523,
 258: [664, -334, -198, -13, 374],
 259: [683, 810, 616, 584],
 260: [-268, -278, -37, 421, 744],
 261: [593, 887],
 262: [-273, 694, -323, -351],
 263: [-443, 492, -266],
 264: 1092,
 265: [-388, -124, -22, 162, -147],
 266: -28,
 267: -603,
 "currency": "EURO",
 268: [-172, -248, -170, -16],
 269: False,
 270: [248, -239],
 271: [-429, -70],
 272: [264, 851, 923, 388],
 273: [533, 899, 677, 61],
 274: [126, -93, 907, 916],
 275: [877, -483, -124, 409, 699],
 276: [316, 746, -405, 536, 950],
 277: [-132, -11, 393, -15, -255],
 278: [-304, -319],
 279: [-4, 566],
 280: [8, 966, -474],
 281: [256, 144, -99, 400],
 282: [-423, -155, 688],
 283: [-455, -377],
 284: [350, -135, 158],
 285: 1129,
 286: [-383, 487, -397, 66, 980],
 287: -226,
 288: [492, -91, 742],
 298: [172, 932, -12],
 299: 1034,
 300: [-1, 419, -59, 934],
 301: [373, -471],
 302: [82, 942, -61],
 303: 1041,
 "year": 2022,
 304: [353, 625, 257, 613, -480],
 305: [782, -372, 218, 538],
 306: [137, -461, 294, 955, 485],
 307: 522,
 308: [182, 386, 620, 170],
 309: -538,
 310: [532, 355, 325, -302, 396],
 311: [-14, -6, 390, 681, 445],
 312: [-65, 264, 635, -133, 293],
 313: [433, -368, -348, -496, 753],
 314: -488,
 317: [366, 988, -324, 727, 159],
 318: 165,
 319: [-228, -459, 703],
 320: [-440, 768, 258],
 321: [644, -310],
 322: [-141, -209, 850, 96, -301],
 323: [318, 446],
 324: -46,
 325: 76,
 326: [431, 984, 551, 450],
 327: [544, 414, 365, 827, 263],
 328: [-81, -35, 858, 866],
 329: [21, -53],
 330: [-387, 150, -378, 843],
 331: [436, 26, 401, -30],
 332: [163, -74],
 333: [978, -175, 591, 952, -465],
 334: [100, 438, -223],
 335: [446, -388, -452, 680, 285],
 336: [-71, 766, 778, 99],
 337: [963, 903, -474, -224],
 338: 294,
 341: [240, -290, 304, -88, 625],
 342: [823, 999],
 343: [437, -29, 296, 837, 660],
 344: -516,
 345: -91,
 346: [648, 10],
 347: 1161,
 348: [447, -207, -446],
 349: [-462, -49],
 350: -413,
 351: [25, -76, -248, -322],
 352: [-272, 376],
 353: -212,
 354: 525,
 "private_account": True,
 "business_account": False,
 355: "-210",
 356: "1062",
 357: [502, 8, -255, 621],
 358: [244, -35],
 359: [-413, -387, 148, 205],
 360: [188, 510, 50, 946, -389],
 361: [-79, 140, 237, 186, 304],
 362: False,
 363: [576, 444, 570],
 364: -338}

In [ ]:
# 2.1. delete key value pairs if key is not an integer in the range from 0 to 364

In [ ]:
# 2.2. add missing key-value pairs

In [ ]:
# 2.3. check the types of all values - if str, convert to int

In [ ]:
# 2.4. create the bank_balance dictionary

In [ ]:
# 2.5. count days with no transactions
# Days with no transactions have the boolean False as value

In [ ]:
# 2.5. count days with account balance > 200.000

In [ ]:
# 2.5. balance on evening of December 31

In [ ]:
# 2.5. sum of withdrawals

In [ ]:
# 2.5. sum of deposits

## Task 5: Coding on paper

This is an exam question from last year's **PEN AND PAPER** exam. Please try to solve this with "pen and paper"! Write down your answers. Then, check (by implementing the code in Python) whether your answers were correct.

```python
i=0
while i<=9:
    print("*"*i)
    i = i+1
```
**Q1** How many times does the above while loop execute exactly?

**Q2** What does the code print out? In particular, what exactly is printed in the last line?

**Q3**  Write an implementation for the same functionality by replacing the while loop with a for loop.

YOUR ANSWER HERE

In [ ]:
# try out the code here